name: Publish Pulumi Plugin

on:
  workflow_dispatch:
  push:
    paths:
      - pulumi/**

# TODO: add job to run tests, push depends on it

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name: Run tests
        working-directory: ./pulumi
        run: npm test
  push_main_to_registry:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'arc-')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./pulumi/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: architectio/pulumi-plugin:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
